### ISSUE TITLE
gtk+-quartz build fails on Mavericks - can't find atk

### ISSUE THREAD

**Issue by soliac** [acornejo/homebrew-quartz#5]
I'm trying to build inkscape-quartz on OS X Mavericks (10.9.2), and it gets to gtk+-quartz & fails during configure:

configure: error: Package requirements (glib-2.0 >= 2.28.0    atk >= 1.29.2    pango >= 1.20    cairo >= 1.6    gdk-pixbuf-2.0 >= 2.21.0) were not met:
No package 'atk' found

I tried "brew install atk", but it didn't help...

**Comment by acornejo** [comment]
I just made atk mandatory (used to be optional), not sure if that will work. Please update your formula and try again.

I will look into this now (haven't used this repository in years)

**Comment by acornejo** [comment]
Fixed the problem. Unfortunately for different reasons it seems inkscape stable will not build on mavericks due to compiler issues (apple uses clang, not gnu-gcc, gcc and g++ are just aliases to clang and clang++).

**Comment by soliac** [comment]
Thanks for that! Now gtk+-quartz builds :). I saw that inkscape stable has issues building with clang. But this is apparently fixed in inkscape dev - I might try stumble ahead and get that to compile. Any hints for modifying this formula for latest inkscape? Maybe it could do a bzr checkout & build from that, dunno.

**Comment by acornejo** [comment]
Yea, that is a separate issue altogether.

It requires bumping the versions of all the formulas to even get that far.

I tried it, but couldn't get rid of all errors.

If you want to give it a shot, checkout the devel branch of this repository, it contains formulas to build inkscape-devel.

**Comment by soliac** [comment]
I got it to build, needed a:
depends_on :libtool
(not sure if did that right), and:
ENV.prepend 'LIBS', '-liconv'

Bigger problem: opens up X11 (!!) & crashes with:
Assertion failed: (CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&pattern->ref_count)), function cairo_pattern_destroy, file cairo-pattern.c, line 822.

So.... not sure where to go from here.

**Comment by acornejo** [comment]
Hi Soliac,

You definitely need libtool, but you need a lot of other things.

The fact that it opened up X11 means that you did not use the quartz flags properly.

Also, without patching the sourcecode, or changing compilers, I don't think you can get it to compile.

As I said, I tried this with the inkscape development version, but got different problems. If you want to see how far I could get, download these formulas:

https://github.com/acornejo/homebrew-quartz/archive/devel.zip

**Comment by soliac** [comment]
Hi acornejo,

I forgot to mention that I am working from your devel branch - so I am using those formulae already. (Stable is a lost cause at this point due to clang issue).

Homebrew is definitely compiling from latest bzr inkscape.dev. I don't know the proper flags to put into the formula to make it use quartz though. I note that there is nothing in inkscape-quartz.rb that mentions quartz or macosx. So I'm stuck same as you I guess? But it does build, so that's something.

**Comment by acornejo** [comment]
Ahh, maybe I can help then!!

You mentioned you got it to compile. How? Would you mind sharing your modified formulas, so I can see if I can fix them to get past the x11/quartz issue?

**Comment by soliac** [comment]
Not sure how to send the file, just gonna paste it (sorry): [inkscape-quartz.rb]:

require 'formula'

class InkscapeQuartz < Formula
  homepage 'http://www.inkscape.org'
  url "http://bazaar.launchpad.net/~inkscape.dev/inkscape/trunk/", :revision => '13165', :using => :bzr
  version 'trunk-r13165'

  # Inkscape is a meaty bastard.
  depends_on 'pkg-config' => :build
  depends_on 'intltool' => :build
  depends_on 'boost-build' => :build
  depends_on :autoconf
  depends_on :automake

  depends_on :libtool #added
  depends_on 'mm-common' #added (not sure if needed)
  depends_on 'gobject-introspection' #added (not sure if needed)
  depends_on 'icu4c' #added (not sure if needed)
  depends_on 'little-cms' #added (not sure if needed)

  depends_on :x11
  depends_on 'bdw-gc'
  depends_on 'boost'
  depends_on 'gsl'
  depends_on 'hicolor-icon-theme'
  depends_on 'little-cms'
  depends_on 'libwpg'
  depends_on 'popt'

  depends_on 'acornejo/quartz/cairomm-quartz'
  depends_on 'acornejo/quartz/pango-quartz'
  depends_on 'acornejo/quartz/gtkmm-quartz'
  depends_on 'acornejo/quartz/librsvg-quartz'
  depends_on 'acornejo/quartz/poppler-quartz'

  def install
    ENV.x11
    ENV.prepend 'CXXFLAGS', '-std=c++11'
    ENV.prepend 'LIBS', '-liconv' #added (not sure if needed)
    args = ["--disable-debug", "--disable-dependency-tracking", "--prefix=#{prefix}"]
    system "./autogen.sh"
    system "./configure", *args
    system "make install"
  end
end

**Comment by acornejo** [comment]
Thanks Luke,

It seems you didn't patch it anything, but instead are just using a
later revision (13165). I chose revision 12x because the launchpad
forums supposedly that revision was building successfuly in mavricks.

I'll try with the latest branch and see if I run into the same problems
you did. I'll keep you posted.

**Comment by soliac** [comment]
Just a note for anyone who is looking at doing this, check out https://code.launchpad.net/~suv-lp/inkscape/osxmenu where there is a link to latest (testing, but seems to work) DMG's at https://www.dropbox.com/sh/b7tyrnugif2ywqj/qpMx1ygywo
